Repository doorkeeper-gem/doorkeeper, pull requests merged in 2018-03, with the labels that each got.

#907 Fix lookup for matching tokens when application has additional scopes
  NEWS.md
  lib/doorkeeper/models/access_token_mixin.rb
  spec/lib/oauth/authorization_code_request_spec.rb
  spec/lib/oauth/client_credentials/creator_spec.rb
  spec/models/doorkeeper/access_token_spec.rb
  spec/requests/flows/skip_authorization_spec.rb
Labels: bug?

#992 Rails API support
  app/controllers/doorkeeper/application_controller.rb
  app/controllers/doorkeeper/authorizations_controller.rb
  lib/doorkeeper/config.rb
  lib/doorkeeper/oauth/error_response.rb
  lib/doorkeeper/oauth/pre_authorization.rb
  lib/doorkeeper/rails/routes.rb
  spec/controllers/authorizations_controller_spec.rb
  spec/lib/config_spec.rb
  spec/lib/oauth/pre_authorization_spec.rb
Labels: feature, needs work

#1049 Adds custom expiration time based on grant type
  NEWS.md
  lib/doorkeeper.rb
  lib/doorkeeper/config.rb
  lib/doorkeeper/oauth.rb
  lib/doorkeeper/oauth/authorization/token.rb
  lib/doorkeeper/oauth/authorization_code_request.rb
  lib/doorkeeper/oauth/base_request.rb
  lib/doorkeeper/oauth/client_credentials/issuer.rb
  lib/doorkeeper/oauth/password_access_token_request.rb
  lib/doorkeeper/oauth/refresh_token_request.rb
  lib/generators/doorkeeper/templates/initializer.rb
  spec/controllers/authorizations_controller_spec.rb
  spec/lib/oauth/authorization_code_request_spec.rb
  spec/lib/oauth/base_request_spec.rb
  spec/lib/oauth/client_credentials/issuer_spec.rb
  spec/lib/oauth/client_credentials_request_spec.rb
  spec/lib/oauth/password_access_token_request_spec.rb
  spec/lib/oauth/refresh_token_request_spec.rb
  spec/lib/oauth/token_request_spec.rb
Labels: enhancement

#1010 Configuration to enforce application scopes
  NEWS.md
  config/locales/en.yml
  lib/doorkeeper/config.rb
  lib/doorkeeper/orm/active_record/application.rb
  lib/generators/doorkeeper/templates/initializer.rb
  spec/dummy/config/initializers/doorkeeper.rb
  spec/requests/applications/applications_request_spec.rb
Labels: enhancement
