Repository doorkeeper-gem/doorkeeper, pull requests merged in 2018-07, with the labels that each got.

#1116 Jw revoke patch
  NEWS.md
  app/controllers/doorkeeper/authorized_applications_controller.rb
  lib/doorkeeper/models/access_grant_mixin.rb
  lib/doorkeeper/orm/active_record/application.rb
  spec/models/doorkeeper/access_grant_spec.rb
  spec/models/doorkeeper/access_token_spec.rb
  spec/models/doorkeeper/application_spec.rb
Labels: enhancement

#1114 Uses `expires_in` on token show endpoint for consistency
  NEWS.md
  lib/doorkeeper/models/access_token_mixin.rb
  spec/models/doorkeeper/access_token_spec.rb
Labels: refactor

#1123 Add note about Rails CSRF protections
  README.md
Labels: docs, enhancement
